<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="BudgetManager.Infrastructure.Tests" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="MailKit" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
	<PackageReference Include="Microsoft.AspNetCore.Identity.UI" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="SkiaSharp" />
  </ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\BudgetManager.Application\BudgetManager.Application.csproj" />
  </ItemGroup>
	
  <ItemGroup>
    <EmbeddedResource Include="Email\Assets\budget-manager-banner.png">
      <LogicalName>BudgetManager.Infrastructure.Email.Assets.budget-manager-banner.png</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Email\Templates\*.html">
		<WithCulture>false</WithCulture>
		<LogicalName>BudgetManager.Infrastructure.Email.Templates.%(Filename)%(Extension)</LogicalName>
	</EmbeddedResource>
    <EmbeddedResource Include="Email\Templates\*.txt">
		<WithCulture>false</WithCulture>
		<LogicalName>BudgetManager.Infrastructure.Email.Templates.%(Filename)%(Extension)</LogicalName>
	</EmbeddedResource>
  </ItemGroup>

</Project>
